#!/usr/bin/env node
/**
 * Every platform contract method an app can call must be reachable through this
 * package's platform-*-surface.ts, and the surfaces must not call a method the
 * contract does not expose.
 *
 * A surface that is missing a method makes that part of the contract unusable
 * from an app. A surface that invents one produces a call that faults at
 * runtime. Neither shows up in a type check, because the method names are
 * strings on the wire.
 *
 * The contract half comes from docs/contracts/platform-abi-surface.json, which
 * neo-os-contracts generates from its compiled manifests and this package
 * vendors - see scripts/lib/vendored-from-contracts.test.mjs for the pin that
 * keeps the two copies together.
 *
 * This replaces seven near-identical audit_platform_<name>_framework.mjs scripts
 * that lived in neo-os-web. They each also read one named app's source (for
 * instance apps/timestamp-proof/src/...) to check that app wired the surface up.
 * That belongs to the app repos: the platform layer must not know which apps
 * exist. Those assertions are not reproduced here.
 *
 *   node scripts/audit_platform_surface_parity.mjs [--check]
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");

const SURFACE_FILES = {
  MiniAppFactory: "framework/platform-factory-surface.ts",
  PlatformAnchor: "framework/platform-anchor-surface.ts",
  PlatformDeFi: "framework/platform-defi-surface.ts",
  PlatformEscrow: "framework/platform-escrow-surface.ts",
  PlatformSocial: "framework/platform-social-surface.ts",
  PlatformVesting: "framework/platform-vesting-surface.ts",
};

// PlatformRegistry has no app-facing surface: apps are registered by the
// platform operator, not by themselves. Listing it here rather than leaving it
// out silently keeps the omission a decision instead of an oversight.
const NO_SURFACE = ["PlatformRegistry"];

// NEP-17 transfers go to the token contract, not to a platform contract, so
// `transfer` is expected in a surface and absent from the contract's own ABI.
const NATIVE_OPERATIONS = new Set(["transfer"]);

// Two call shapes are in use: read("method", ...) and read(network, "method",
// ...). Both are matched, since a surface may use either and neither is wrong.
const OPERATION = /\b(?:read|invoke)\(\s*(?:[A-Za-z_$][\w$]*\s*,\s*)?"([A-Za-z0-9_]+)"/g;

function surfaceOperations(relativePath) {
  const source = fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
  const found = [...source.matchAll(OPERATION)].map((match) => match[1]);
  return {
    methods: [...new Set(found.filter((name) => !NATIVE_OPERATIONS.has(name)))].sort(),
    native: found.filter((name) => NATIVE_OPERATIONS.has(name)),
  };
}

export function evaluateParity({ abiSurface, surfaces }) {
  const contracts = {};
  for (const [contract, relativePath] of Object.entries(surfaces)) {
    const abi = abiSurface[contract];
    if (!abi) {
      contracts[contract] = {
        passed: false,
        error: `${contract} has no entry in the vendored ABI surface`,
      };
      continue;
    }
    const { methods, native } = surfaceOperations(relativePath);
    const abiSet = new Set(abi);
    const surfaceSet = new Set(methods);
    const missing = abi.filter((name) => !surfaceSet.has(name));
    const extra = methods.filter((name) => !abiSet.has(name));

    contracts[contract] = {
      passed: missing.length === 0 && extra.length === 0 && methods.length > 0,
      source: relativePath,
      abi_method_count: abi.length,
      surface_method_count: methods.length,
      native_operations: native,
      missing_methods: missing,
      extra_methods: extra,
    };
  }

  const covered = Object.keys(surfaces).length;
  return {
    // A run that checked nothing must not read as a pass.
    passed: covered > 0 && Object.values(contracts).every((entry) => entry.passed),
    contract_count: covered,
    contracts_without_surface: NO_SURFACE,
    contracts,
  };
}

function main() {
  const abiSurfacePath = path.join(repoRoot, "docs/contracts/platform-abi-surface.json");
  if (!fs.existsSync(abiSurfacePath)) {
    console.error(
      `${path.relative(repoRoot, abiSurfacePath)} is missing. It is generated by ` +
        `neo-os-contracts (scripts/generate_platform_abi_surface.mjs) and vendored here.`,
    );
    process.exit(1);
  }
  const abiSurface = JSON.parse(fs.readFileSync(abiSurfacePath, "utf8")).contracts;
  const report = evaluateParity({ abiSurface, surfaces: SURFACE_FILES });

  if (process.argv.includes("--check")) {
    if (!report.passed) {
      for (const [contract, entry] of Object.entries(report.contracts)) {
        if (entry.passed) continue;
        console.error(`${contract}: ${entry.error ?? ""}`);
        if (entry.missing_methods?.length) {
          console.error(`  unreachable from ${entry.source}: ${entry.missing_methods.join(", ")}`);
        }
        if (entry.extra_methods?.length) {
          console.error(`  not in the contract ABI: ${entry.extra_methods.join(", ")}`);
        }
      }
      process.exit(1);
    }
    const counts = Object.entries(report.contracts)
      .map(([name, entry]) => `${name} ${entry.abi_method_count}`)
      .join(", ");
    console.log(`platform surface parity ok: ${counts}`);
    return;
  }

  console.log(JSON.stringify(report, null, 2));
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  main();
}
